FROM node:23-alpine

WORKDIR /app

COPY package.json .

RUN npm install --force

RUN npm install --global vite

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host=0.0.0.0", "--port=5173"]
