FROM node:23-alpine

WORKDIR /app

# Install system dependencies
RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    wget

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host=0.0.0.0", "--port=8080"]
