services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend:
    depends_on:
      - backend
    build: ./frontend/
    ports:
      - '8080:8080'

    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000

